// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $("#slider").slider({
      value: 200,
      min: 0,
      max: 500,
      step: 1,
      slide: function(event, ui) {
        return $("#amount").val(ui.value);
      }
    }).smoothsnap();
    return $("#amount").val($("#slider").slider("value"));
  });

}).call(this);
