// Generated by CoffeeScript 1.6.3
(function() {
  $.widget('ui.smoothsnap', {
    _create: function() {
      var startPosition,
        _this = this;
      startPosition = 0;
      this.element.on("slidestart", function(event, ui) {
        startPosition = ui.value;
        return _this._setStep(_this.element, 1);
      });
      return this.element.on("slide", function(event, ui) {
        if (_this._scrollAmount(startPosition, ui.value) <= 10) {
          return _this._setStep(_this.element, 1);
        } else if (_this._scrollAmount(startPosition, ui.value) <= 50) {
          return _this._setStep(_this.element, 10);
        } else {
          return _this._setStep(_this.element, 50);
        }
      });
    },
    _scrollAmount: function(start, current) {
      return Math.abs(current - start);
    },
    _setStep: function(element, val) {
      return element.slider("option", "step", val);
    }
  });

}).call(this);
