// Generated by CoffeeScript 1.6.3
(function() {
  $.widget('ui.smoothsnap', {
    _create: function() {
      var element, scrollAmount, setStep, startPosition;
      element = this.element;
      startPosition = 0;
      element.on("slidestart", function(event, ui) {
        startPosition = ui.value;
        return setStep(element, 1);
      });
      element.on("slide", function(event, ui) {
        if (scrollAmount(ui.value) <= 10) {
          return setStep(element, 1);
        } else if (scrollAmount(ui.value) <= 50) {
          return setStep(element, 10);
        } else {
          return setStep(element, 50);
        }
      });
      scrollAmount = function(current) {
        return Math.abs(current - startPosition);
      };
      return setStep = function(element, val) {
        return element.slider("option", "step", val);
      };
    }
  });

}).call(this);
